# SPDX-License-Identifier: MIT
# yaml-language-server: $schema=https://stack.lol/schemas/stack.config.schema.yaml
# This is a https://stack.lol stack metadata file.
status: starting
slug: d2
name: D2
flavor: DockerCompose
version: "latest"
updated_at: 2026-08-12
description: Turn text into diagrams
author: Terrastruct, Inc
license: MPL-2.0
homepage: https://d2lang.com
repository: https://github.com/d2lang/d2
stars: 25000
tags: [diagram]
alternativeTo: [miro, lucidchart, visio]
readme: |

  A modern diagram scripting language that turns text to diagrams.

  ![preview](https://victorbjorklund.com/assets/images/d2/build-diagrams-as-code-with-d2-d2lang--1592893463.svg)

  <hr>

  ### Features

  - 📝 **Text-based**: Write diagrams in plain text, no need to drag and drop.
  - 🎨 **Beautiful themes**: Production-ready themes by professional designers.
  - ✏️ **Sketch mode**: A beautiful, hand-drawn aesthetic.
  - 🎬 **Animations**: Animated diagrams from text.
  - 📐 **LaTeX**: Perfect for academic use and research papers.
  - 🌐 **Any language**: Supports almost all languages.
  - 💻 **Code snippets**: Syntax highlighted code right in the diagram.
  - 📄 **Markdown**: Include longform explanations with Markdown.
  - 📊 **Tables**: Show structured data like SQL tables.
