# SPDX-License-Identifier: MIT
# yaml-language-server: $schema=https://stack.lol/schemas/stack.config.schema.yaml
# This is a https://stack.lol stack metadata file.
slug: dashy
name: Dashy
icon: 🚀
flavor: DockerCompose
version: "3.1.1"
updated_at: 2024-05-30
description: Personal dashboard
author: Alicia Sykes
license: MIT
homepage: https://dashy.to
repository: https://github.com/Lissy93/dashy
stars: 26400
tags: [dashboard]
alternativeTo: []
readme: |

  Dashy helps you organize your self-hosted services by making them accessible from a single place.

  ![preview](https://github.com/Lissy93/dashy/blob/master/docs/showcase/5-project-management.png?raw=true)

  <hr>

  ### Features

  - 📃 Support for multiple pages
  - 🚦 Real-time status monitoring for each of your apps/links
  - 📊 Use widgets to display info and dynamic content from self-hosted services
  - 🔎 Instant search by name, domain, or tags + customizable hotkeys & keyboard shortcuts
  - 🎨 Many built-in color themes, with UI color editor and support for custom CSS
  - 🧸 Many icon options - Font-Awesome, homelab icons, auto-fetching Favicon, images, emojis, etc.
  - 💂 Optional authentication with multi-user access, configurable privileges, and SSO support
  - 🌎 Multi-language support, with 10+ human-translated languages, and more on the way
  - ☁ Optional, encrypted, free off-site cloud backup and restore feature available
  - 💼 A workspace view, for easily switching between multiple apps simultaneously
  - 🛩️ A minimal view, for use as a fast-loading browser Startpage
  - 🖱️ Choose app launch methods: new tab, same tab, clipboard, pop-up modal, or open in workspace view
  - 📏 Customizable layout, sizes, text, component visibility, sort order, behavior, etc.
  - 🖼️ Options for a full-screen background image, custom nav-bar links, HTML footer, title, etc.
  - 🚀 Easy to setup with Docker, or on bare metal, or with 1-Click cloud deployment
  - ⚙️ Easy single-file YAML-based configuration, and option to configure app through the UI
  - ✨ Under active development with improvements and new features added regularly
  - 🤏 Small bundle size, fully responsive UI, and PWA for basic offline access
  - 🆓 100% free and open-source
  - 🔐 Strong focus on privacy
  - 🌈 And loads more...
